# Generated by Django 6.0.6 on 2026-06-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.CharField(blank=True, max_length=50)),
                ('notice_period', models.CharField(blank=True, max_length=50)),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_link', models.CharField(blank=True, max_length=500)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
