# Generated by Django 6.0.6 on 2026-06-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_department_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Warehouse Supervisor'), ('STAFF', 'Staff'), ('PICKER', 'Picker/Operator'), ('AUDITOR', 'Auditor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
