# Generated by Django 6.0.6 on 2026-06-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('MANAGER', 'Warehouse Manager'), ('SUPERVISOR', 'Warehouse Supervisor'), ('STAFF', 'Warehouse Staff'), ('PICKER', 'Picker / Operator'), ('AUDITOR', 'Auditor'), ('OTHER', 'Other')], max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('CONTACTED', 'Contacted'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
