# Generated by Django 6.0.6 on 2026-07-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_manager_fk_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('A', 'Zone A'), ('B', 'Zone B')], default='A', max_length=1),
        ),
    ]
