# Generated by Django 6.0.6 on 2026-07-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_zone_zone_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['id']},
        ),
    ]
