# Generated by Django 6.0.6 on 2026-06-19 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='System Alert', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('SPACE_FULL', 'Space Full Alert'), ('REPORT_READY', 'Report Ready'), ('SYSTEM', 'System Message')], default='SYSTEM', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
